### ISSUE TITLE
The essence of double finite scaling phenomenon

### ISSUE THREAD

**Issue by JerryChen97** [JerryChen97/KitaevLadder#32]
When I was doing the finite scaling of spin-1 Kitaev ladder, I encountered again the result that the entanglement entropy suddenly jumped down and increased again along with the bond dimension.
![image](https://user-images.githubusercontent.com/21050723/89242416-7ff60e80-d5cf-11ea-8a34-bf76fb120099.png)

This is not the first time we noticed it. The same situations happened for the spin-1/2 cases occasionally. I am wondering what is the reason and the essence of such phenomena.

**Comment by JerryChen97** [comment]
I have also thought about the possibility that the first several tries served as the preparation run of DMRG; but still I also remember that in the past I had observed more than twice jumps in one simulation.

**Comment by JerryChen97** [comment]
Cat states?

**Comment by JerryChen97** [comment]
Entanglement Spectra

**Comment by JerryChen97** [comment]
Plot: chi-dependent corr & entropy + energy

**Comment by JerryChen97** [comment]
I just checked the energy evolution w.r.t. the bond dims and found that indeed the first several results were not really accurate. Intuitively I will take them as the preparation states and just discard afterwards.
![image](https://user-images.githubusercontent.com/21050723/91110529-1ad08e80-e64c-11ea-967c-f1aca4ebf27f.png)

![image](https://user-images.githubusercontent.com/21050723/91110539-2459f680-e64c-11ea-92b7-a94f43b2edf9.png)

![image](https://user-images.githubusercontent.com/21050723/91110552-2ae86e00-e64c-11ea-9683-ec474f3ea6e3.png)

**Comment by JerryChen97** [comment]
@aaronszasz Do you think this makes sense?

**Comment by aaronszasz** [comment]
Can you zoom in on the energy plot around the point where the entanglement drops?

**Comment by JerryChen97** [comment]
> Can you zoom in on the energy plot around the point where the entanglement drops?

Cool. I will try increasing chi 1 by 1 from 8 to 50

**Comment by JerryChen97** [comment]
When I zoom in by taking a smaller step (`dchi=1`) from 8 to 50, the results were quite different...
![image](https://user-images.githubusercontent.com/21050723/91112397-03e06b00-e651-11ea-96a9-625669999782.png)
![image](https://user-images.githubusercontent.com/21050723/91112404-09d64c00-e651-11ea-9b2c-61a78d0b7840.png)
![image](https://user-images.githubusercontent.com/21050723/91112414-12c71d80-e651-11ea-9529-ef9f7549639e.png)

**Comment by JerryChen97** [comment]
But the scaling seems much more stable:
![image](https://user-images.githubusercontent.com/21050723/91112448-27a3b100-e651-11ea-88c0-d678c38099eb.png)

**Comment by JerryChen97** [comment]
> But the scaling seems much more stable:
> ![image](https://user-images.githubusercontent.com/21050723/91112448-27a3b100-e651-11ea-88c0-d678c38099eb.png)

The first 8 points were discarded in this scaling

**Comment by JerryChen97** [comment]
@aaronszasz How do you like it? I feel this convinces that for such a gapless point (or near-gapless) the first several runs are actually preparation...

**Comment by aaronszasz** [comment]
It seems that when you increase the bond dimension by the smaller amount, it switches to the correct ground state sooner, but it seems to reach the same kind of correct state in the end.  So I will believe this scaling.

To be honest this is not what I meant by "zoom in" ... but it's actually very nice to see, so thanks!  What I had intended was just the data from the first energy figure, but with the y axis set to show only near the energy that you have around chi=50, to hopefully see what looks like a discontinuity in the energy.  The new data does seem to show this, with the jump from in energy between chi=8 and 9.

**Comment by aaronszasz** [comment]
I don't know if you can conclude in general that the first several bond dims are always going to be useless except as preparation, but it is convincing that you need to at least be careful and check the evolution with bond dimension for jumps, at least at some points.  I think though that if you can do this very carefully at one point in a phase and then use that wf to start nearby points, that should be ok.

**Comment by JerryChen97** [comment]
> I don't know if you can conclude in general that the first several bond dims are always going to be useless except as preparation, but it is convincing that you need to at least be careful and check the evolution with bond dimension for jumps, at least at some points. I think though that if you can do this very carefully at one point in a phase and then use that wf to start nearby points, that should be ok.

Yeah it's true. In the past, the usual number of 'preparation' steps will be like one or two (especially for those gapped points), but for this point apparently only after 8 or even more we can take the result as correct. I think maybe during the finite-scaling we should dynamically measure the change of energy to make sure the output will be reliable (like deltaE < 1e-6 or so).

**Comment by aaronszasz** [comment]
Yes, that seems like a good idea.  In general I'm not too worried about it though, if you're doing a full phase diagram, since it's extremely unlikely that a metastable state would persist for a whole phase, so the problem should be easily visible and therefore correctable.
